---
- name: Create the iptables file
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: mongodb | group add
  group: name={{mongodb_user}}  state=present

- name: Create mongodb user
  user: name={{mongodb_user}} group={{mongodb_user}} state=present

- name: Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/mongodb.conf
  when: mongodb_logrotate

- name: Configure database directory
  file: state=directory path={{ mongodb_conf_dbpath }} owner={{mongodb_user}} group={{mongodb_user}} mode=0755

- name: Configure log directory
  file: state=directory path={{ mongodb_conf_logpath | dirname }} owner={{ mongodb_user }} group={{ mongodb_user }} mode=0757

- name: Configure mongodb
  template: src=mongod.conf.j2 dest=/etc/mongod.conf owner={{ mongodb_user }} group={{ mongodb_user }} mode=0644
  notify: mongodb restart

- name: Ensure mongodb is started
  service: name={{ mongodb_daemon_name }} state=started enabled=yes
  changed_when: False

#- name: Pause for a while
#  pause: seconds=5

- name: add admin mongodb
  mongodb_user: database={{ mongodb_admin_database }} name={{ mongodb_admin_user }} password={{ mongodb_admin_pswd }} roles='root' state=present
  notify: mongodb restart
  sudo: yes

- name: Run mongoshell commands
  command: mongo {{ item.key }} --eval "{{ item.value|join('\n') }}"
  with_dict: mongodb_shell
